name: validations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.1

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: v18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Validate JSON
        run: pnpm run ocean --validate